# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10d29d650a7916ffce82126a718a4a6b4634852412884555f82fa19e29cf9c65d27f1d6dc450e755a7d8cc2e436bb61cd766953289108a6f1161d505b7df8545

test:
  secret_key_base: a6ca178517ce2ebced6d42b773f4f91ec1b4447b0da19865f936af10e0ac149bc8ff2872b865e2b0c48724174d4360b9e6374ca10f654ee16f1cf5726ce73d4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
